// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqSLhJ2IUbAejHpTAob3YMe7lqbfPZfHw',
    appId: '1:266173993687:web:ebbb57d623f5b75303d692',
    messagingSenderId: '266173993687',
    projectId: 'projeto-egg',
    authDomain: 'projeto-egg.firebaseapp.com',
    storageBucket: 'projeto-egg.appspot.com',
    measurementId: 'G-XVY0LJB16L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbP44XPoU7DFG7yHFCT1WXmETyBTDpGvA',
    appId: '1:266173993687:android:b17be68b3e67f70903d692',
    messagingSenderId: '266173993687',
    projectId: 'projeto-egg',
    storageBucket: 'projeto-egg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE845SyWwR-1QqzTFnngDZeERtHxEgw34',
    appId: '1:266173993687:ios:db61ba9175fd486f03d692',
    messagingSenderId: '266173993687',
    projectId: 'projeto-egg',
    storageBucket: 'projeto-egg.appspot.com',
    iosClientId: '266173993687-i07s19tls65b3skspsm5h099epf2l7h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopeggs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE845SyWwR-1QqzTFnngDZeERtHxEgw34',
    appId: '1:266173993687:ios:db61ba9175fd486f03d692',
    messagingSenderId: '266173993687',
    projectId: 'projeto-egg',
    storageBucket: 'projeto-egg.appspot.com',
    iosClientId: '266173993687-i07s19tls65b3skspsm5h099epf2l7h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopeggs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqSLhJ2IUbAejHpTAob3YMe7lqbfPZfHw',
    appId: '1:266173993687:web:efcead23c2adb96403d692',
    messagingSenderId: '266173993687',
    projectId: 'projeto-egg',
    authDomain: 'projeto-egg.firebaseapp.com',
    storageBucket: 'projeto-egg.appspot.com',
    measurementId: 'G-GTQDCCC3TX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBqSLhJ2IUbAejHpTAob3YMe7lqbfPZfHw',
    appId: '1:266173993687:web:e26ee2e4ec04178e03d692',
    messagingSenderId: '266173993687',
    projectId: 'projeto-egg',
    authDomain: 'projeto-egg.firebaseapp.com',
    storageBucket: 'projeto-egg.appspot.com',
    measurementId: 'G-RXTMCDEFH0',
  );
}
